import React from 'react';
import { ArrowLeft, Calendar, Clock } from 'lucide-react';
import { Link } from 'react-router-dom';

const CollegeTradingCompetitions = () => {
  return (
    <div className="blog-minimal relative min-h-[100dvh] text-slate-300 font-sans selection:bg-[#f3ede4] selection:text-[#3a2a1e]">
      {/* Solid base background */}
      <div className="fixed inset-0 bg-[#1a3016] z-0"></div>

      {/* Dynamic Animated Background */}
      <div className="fixed inset-0 z-0 overflow-hidden pointer-events-none w-full h-full">
        <div className="absolute top-[-20%] left-[-20%] w-[60vw] h-[60vw] bg-[#2a4822] rounded-full blur-[100px] animate-blob mix-blend-screen"></div>
        <div className="absolute top-[-20%] right-[-20%] w-[55vw] h-[55vw] bg-[#3e6034] rounded-full blur-[100px] animation-delay-2000 mix-blend-screen"></div>
        <div className="absolute bottom-[-30%] left-[15%] w-[70vw] h-[70vw] bg-[#0e1e0c] rounded-full blur-[100px] animation-delay-4000 mix-blend-screen"></div>
        <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 brightness-100 contrast-150 mix-blend-overlay"></div>
      </div>

      {/* Navigation */}
      <nav className="fixed w-full z-50 bg-black/40 backdrop-blur-xl border-b border-white/5 py-4">
        <div className="max-w-5xl mx-auto px-6 flex items-center gap-4">
          <Link to="/blog" className="flex items-center gap-2 text-[#c4d4b8] hover:text-white transition-colors">
            <ArrowLeft size={20} />
            <span className="text-sm font-medium">Back to Blog</span>
          </Link>
        </div>
      </nav>

      {/* Main Content */}
      <main className="relative z-10 w-full pt-32 pb-24">
        <article className="mx-auto w-[min(100%,72rem)] px-4 sm:px-6 lg:px-10 xl:px-12 space-y-8">
          {/* Header */}
          <div className="space-y-6">
            <div className="inline-block px-3 py-1 rounded-full bg-white/5 border border-white/10 text-xs font-medium text-[#8aac78]">
              Experiences
            </div>
            <h1 className="text-4xl md:text-5xl font-bold text-white leading-tight">
              Trading Competitions
            </h1>
            <div className="flex flex-wrap gap-6 text-sm text-slate-400">
              <div className="flex items-center gap-2">
                <Calendar size={16} />
                <span>Month Day, Year</span>
              </div>
              <div className="flex items-center gap-2">
                <Clock size={16} />
                <span>15 min read</span>
              </div>
            </div>
          </div>

          {/* Content */}
          <div className="w-full max-w-none space-y-10 text-[#8aac78] text-lg md:text-xl leading-[1.9]">
            <p>
              Trading competitions can be fairly intense but are definitely fun events to attend and meet others.
            </p>

            <h2 className="text-2xl font-bold text-white mt-8 mb-4">Northwestern (NUTC)</h2>
            <p>
              This was my first trading competition in college. I tried a multitude of strategies and combined simple moving average with some penny stocks and
              mixed and merged popular indicators. I ended up taking third and the winning strategies were either buying a lot and selling later or penny stocks.
              You were given starter code to implement your solutions in and during the competition, it was run against other bots and people.
            </p>
            <h2 className="text-2xl font-bold text-white mt-8 mb-4">Georgia Tech</h2>
            <p>
              There were 3 parts to the competition. The first part was the manual trading side where you had to manually click buying and selling and bots weren't allowed.
              A good strategy was providing liquidity by spamming both buy and sell buttons. The second part was the algorthmic part where bots were allowed. My partner and I ended
              up using a pair trading strategy towards the end which ended up with average PnL. The third part was a more game theory game playing as a table against the others in
              determining who would buy what at what price and get the max amount based on a grid and the actions of others. 
            </p>
            <h2 className="text-2xl font-bold text-white mt-8 mb-4">UChicago</h2>
            <p>
              The competition day was entirely algorithmic made up of complex factors and changing variables. With strucutured and unstructured information, parsing and creating correlation with sin graphs
              seemed to be the strategy. Before the competition day, you could submit the manual portfolio opimization section where rank was measured by sharpe ratio. Since some teams observed the data was
              generated by llms, they were able to replicate and reverse engineering achieving a sharpe ratio as high as the 50s.
            </p>
            <h2 className="text-2xl font-bold text-white mt-8 mb-4">Rutgers</h2>
            <p>
              Fairly new competition where you were also given some source code and you ran your code against bots and other competitors. Had a wide array of types suchs as prediciton markets, 
              ETFs, FX, and single name stocks.
            </p>
            <h2 className="text-2xl font-bold text-white mt-8 mb-4">Prosperity III</h2>
            <p>
              5 rounds eith each lasting 3 days. Has both a manual and algorithmic section where manual is more game theory and based on the 
              decisions others make in the game and the algorithmic section is trading various securities/equities with new types introduced every round in 
              addition to ability to continue trading on the past previous types already introduced. Historical data with past prosperity 
              competitions and advice seemed advantageous and consistency to submit for each round is important.
            </p>


           
            

            
          </div>
        </article>
      </main>
    </div>
  );
};

export default CollegeTradingCompetitions;
